create table mw_error_store
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_stamp date,
entity_tag varchar2(100),
revision_no varchar2(3CHAR),
mw_error number,
percentage_mw_error number,
constraints unique_mw_error unique(time_stamp,entity_tag,revision_no),
constraints pk_mw_error primary key(id)
)